# encoding: utf-8

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "raring"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
  config.ssh.forward_agent = true

  config.vm.provision :shell, :inline => "wget -q -O- http://debs.strawlab.org/astraw-archive-keyring.gpg | sudo apt-key add -"
  config.vm.provision :shell, :inline => "echo \"deb http://debs.strawlab.org/ $(lsb_release -cs)/\" | sudo tee /etc/apt/sources.list.d/strawlab-public.list"
  config.vm.provision :shell, :inline => "sudo apt-get update"

  config.vm.provision :shell, :path => "vagrant_linux_build.sh"

end
